apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello
  template:
    metadata:
      labels:
        app: nginx-hello
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: nginx-hello-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-hello-html
data:
  index.html: |
    <html>
      <body>
        <h1>Hello World from NGINX!</h1>
      </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello
spec:
  type: ClusterIP
  selector:
    app: nginx-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
